name: oidc
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - click
  - tornado
  - pyyaml

  - black
  - flake8
  - isort
  - mypy

  - pip
  - pip:
    - oic>=1.5
    - click-logging
